# Configuracao do banco de dados PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusdb

# Configuracao do Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Configuracao do console do H2 (para desenvolvimento)
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.http.port=8080